#!/bin/sh

set -x

# Couchbase Server start script. 

if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root"
    exit 1
fi

# Create directories where couchbase stores its data
cd /opt/couchbase
mkdir -p var/lib/couchbase \
         var/lib/couchbase/config \
         var/lib/couchbase/data \
         var/lib/couchbase/stats \
         var/lib/couchbase/logs \
         var/lib/moxi
chown -R couchbase:couchbase var

# Increase ulimits
ulimit -n 40960
ulimit -c unlimited
ulimit -l unlimited

# Start couchbase, pass -noinput so it doesn't drop us in the erlang shell
su - couchbase -c "/opt/couchbase/bin/couchbase-server -- -noinput"

echo "couchbase-server finished running"
