#!/bin/sh

# If HOME is set, Erlang requires that it be a writable directory.
# We can't guarantee that as it depends on which UID the container
# is started as. The couchbase-server script will handle it being
# unset, though, so do that for safety.
unset HOME

exec 2>&1

# Create directories where couchbase stores its data
cd /opt/couchbase
mkdir -p var/lib/couchbase \
         var/lib/couchbase/config \
         var/lib/couchbase/data \
         var/lib/couchbase/stats \
         var/lib/couchbase/logs \
         var/lib/moxi

# Ensure everything in var is writable by the 'couchbase' user, and warn when
# encountering files or directories which aren't.
# Skip "inbox" as it may contain readonly-mounted things like k8s certs.
find var -path var/lib/couchbase/inbox -prune -o -print0 | \
  xargs -0 -I {} sh -c '
    if ! test -w "{}"; then
      echo "Warning: '\''$(pwd)/{}'\'' is not writable by user '\''couchbase'\''; this may result in issues" >&2;
    fi'

if [ "$(whoami)" = "couchbase" ]; then
  exec /opt/couchbase/bin/couchbase-server -- -kernel global_enable_tracing false -noinput
else
  exec chpst -ucouchbase  /opt/couchbase/bin/couchbase-server -- -kernel global_enable_tracing false -noinput
fi
